name: Preview for PR
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request_target' && github.event.action != 'closed'
    name: Create preview for PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Comment on opened PR
        if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
        uses: unsplash/comment-on-pr@master
        with:
          msg: "This is a test comment"
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}